#!/bin/sh

# pushes site to GitHub
push() {
    git init
    git remote add origin https://github.com/rp/rp.github.io.git
    git add .
    git commit --allow-empty-message -m ""
    git push --set-upstream origin master --force
    rm -rf .git
}

deploy() {
    cd _site
    push
}

if [ -d "_site" ]; then
    deploy
else
    stack exec site build
    deploy
fi
